### ISSUE TITLE
Instagram API

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#4]
create account

**Comment by MSevey** [comment]
create API Key

**Comment by chanceencounter** [comment]
https://apigee.com/console/instagram?apig_cc=1

Can also use curl commands.
https://curl.haxx.se/docs/

**Comment by chanceencounter** [comment]
https://www.instagram.com/developer/endpoints/users/#get_users

Cleaner JSON information.

**Comment by brookea** [comment]
Important developer info on Instagram. Basically this is what we have to do to get rolling with the IG API:

1. We need to register Mavrck as an IG developer so we can play around in the sandbox mode to receive and manipulate instagram data. 
    + This entails signing up here https://www.instagram.com/developer/register/ = should Brian do this?
    + Having a sandbox means we can only allow 20 users in there and get access to their last 20 posts with their permission only so we won't be able to test out our extension on a lot of people and we most likely have to know these people.
1. We will only be able to get 'basic' permissions for our extension, because as of 10/1/17, IG removed all other types of permissions. This list is here: https://www.instagram.com/developer/authorization/
1. Once we are done with our extension, we have to submit it to IG for them to approve. The process and criteria for that is here: https://www.instagram.com/developer/review/
1. And then once we get approved, we have to do this whole authentication process for users to be able to actually use the extension: https://www.instagram.com/developer/authentication/
1. Basic info on how to make our extension secure: https://www.instagram.com/developer/secure-api-requests/

The main takeaway is that our scope for users while we create this is going to be really limited. Furthermore, some of the data we thought we could get originally might be restricted by IG because they recently made access to their API way more strict.

**Comment by MSevey** [comment]
Check to see if API is versioned to protect against breaks due to updates
